"""
WHILE LOOP IS USED AND EXECUTE A BLOCK OF STATEMENTS WHICH WILL BE USED WHEN IF THE CONDITION 
WHICH IS THERE BECOMES FALSE THEN IT WILL COME OUT OF THE LOOP
THIS WILL BE USED TO TRAVERSE THE DATA CHECK THE CONDITION AND THEN INCREMENT THE VALUES

"""

i = int(input("Please enter the number "))

while i<3:
    print("geeks for geeks")
    i=i+1


