""""
LISTS, TUPLES AND SETS
THINK OF LISTS TUPLES AND SETS AS CONTAINERS WHERE WE CAN NEATLY STORE DIFFERENT TYPES OF INFORMATION,
WE CAN USE LISTS IN MUCH MORE FLEXIBLE WAY ACCORDING TO THE NEED.
WHILE TUPLES ARE MORE LIKE SOLID, UNCHANGING TREASURE CHESTS. THEY HELP US KEEP DATA ORGANIZED AND IT MAKES EASY TO FIND IT.
"""

#LIST EXAMPLE
items_list = ['apple','banana','cherry',5]

#TUPLES EXAMPLE
items_tuple = ('kiwi','grape','pear')


"""

DICTIONARIES: DICTIONARIES ACT LIKE A WELL BEHAVED INFORMATION WHERE EVERYTHING CAN BE LABELED.
INSTEAD OF DINDING INFORMATION BASED ON ITS POSITION WE LOOK IT UP USING THE LABEL 

"""

#declare the dictionary
person_info= {'Name':'Vivekanand Joshi', 'Age':28 , 'Job':'RPA Developer'}
